
python get_noise_data.py  --select_method 'augmentation_width_shift' --save_path_pkl './noisedata/cifar10/augmentation_width_shift_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_height_shift' --save_path_pkl './noisedata/cifar10/augmentation_height_shift_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_horizontal_flip' --save_path_pkl './noisedata/cifar10/augmentation_horizontal_flip_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_vertical_flip' --save_path_pkl './noisedata/cifar10/augmentation_vertical_flip_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_rotation' --save_path_pkl './noisedata/cifar10/augmentation_rotation_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_brightness' --save_path_pkl './noisedata/cifar10/augmentation_brightness_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_zoom' --save_path_pkl './noisedata/cifar10/augmentation_zoom_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_featurewise_std_normalization' --save_path_pkl './noisedata/cifar10/augmentation_featurewise_std_normalization_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_zca_whitening' --save_path_pkl './noisedata/cifar10/augmentation_zca_whitening_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_shear_range' --save_path_pkl './noisedata/cifar10/augmentation_shear_range_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'augmentation_channel_shift_range' --save_path_pkl './noisedata/cifar10/augmentation_channel_shift_range_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'noise_salt_pepper' --save_path_pkl './noisedata/cifar10/noise_salt_pepper_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'noise_gasuss' --save_path_pkl './noisedata/cifar10/noise_gasuss_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'fog' --save_path_pkl './noisedata/cifar10/fog_x.pkl' --img_np_path './data/cifar10_x.pkl'
python get_noise_data.py  --select_method 'contrast' --save_path_pkl './noisedata/cifar10/contrast_x.pkl' --img_np_path './data/cifar10_x.pkl'


python get_noise_data.py  --select_method 'augmentation_width_shift' --save_path_pkl './noisedata/fashionMnist/augmentation_width_shift_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_height_shift' --save_path_pkl './noisedata/fashionMnist/augmentation_height_shift_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_horizontal_flip' --save_path_pkl './noisedata/fashionMnist/augmentation_horizontal_flip_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_vertical_flip' --save_path_pkl './noisedata/fashionMnist/augmentation_vertical_flip_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_rotation' --save_path_pkl './noisedata/fashionMnist/augmentation_rotation_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_brightness' --save_path_pkl './noisedata/fashionMnist/augmentation_brightness_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_zoom' --save_path_pkl './noisedata/fashionMnist/augmentation_zoom_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_featurewise_std_normalization' --save_path_pkl './noisedata/fashionMnist/augmentation_featurewise_std_normalization_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_zca_whitening' --save_path_pkl './noisedata/fashionMnist/augmentation_zca_whitening_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_shear_range' --save_path_pkl './noisedata/fashionMnist/augmentation_shear_range_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'augmentation_channel_shift_range' --save_path_pkl './noisedata/fashionMnist/augmentation_channel_shift_range_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'noise_salt_pepper' --save_path_pkl './noisedata/fashionMnist/noise_salt_pepper_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'noise_gasuss' --save_path_pkl './noisedata/fashionMnist/noise_gasuss_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'fog' --save_path_pkl './noisedata/fashionMnist/fog_x.pkl' --img_np_path './data/fashionMnist_x.pkl'
python get_noise_data.py  --select_method 'contrast' --save_path_pkl './noisedata/fashionMnist/contrast_x.pkl' --img_np_path './data/fashionMnist_x.pkl'



python get_noise_data.py  --select_method 'augmentation_width_shift' --save_path_pkl './noisedata/plant/augmentation_width_shift_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_height_shift' --save_path_pkl './noisedata/plant/augmentation_height_shift_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_horizontal_flip' --save_path_pkl './noisedata/plant/augmentation_horizontal_flip_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_vertical_flip' --save_path_pkl './noisedata/plant/augmentation_vertical_flip_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_rotation' --save_path_pkl './noisedata/plant/augmentation_rotation_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_brightness' --save_path_pkl './noisedata/plant/augmentation_brightness_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_zoom' --save_path_pkl './noisedata/plant/augmentation_zoom_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_featurewise_std_normalization' --save_path_pkl './noisedata/plant/augmentation_featurewise_std_normalization_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_zca_whitening' --save_path_pkl './noisedata/plant/augmentation_zca_whitening_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_shear_range' --save_path_pkl './noisedata/plant/augmentation_shear_range_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'augmentation_channel_shift_range' --save_path_pkl './noisedata/plant/augmentation_channel_shift_range_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'noise_salt_pepper' --save_path_pkl './noisedata/plant/noise_salt_pepper_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'noise_gasuss' --save_path_pkl './noisedata/plant/noise_gasuss_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'fog' --save_path_pkl './noisedata/plant/fog_x.pkl' --img_np_path './data/plant_x.pkl'
python get_noise_data.py  --select_method 'contrast' --save_path_pkl './noisedata/plant/contrast_x.pkl' --img_np_path './data/plant_x.pkl'


python get_noise_data.py  --select_method 'augmentation_width_shift' --save_path_pkl './noisedata/cifar100/augmentation_width_shift_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_height_shift' --save_path_pkl './noisedata/cifar100/augmentation_height_shift_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_horizontal_flip' --save_path_pkl './noisedata/cifar100/augmentation_horizontal_flip_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_vertical_flip' --save_path_pkl './noisedata/cifar100/augmentation_vertical_flip_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_rotation' --save_path_pkl './noisedata/cifar100/augmentation_rotation_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_brightness' --save_path_pkl './noisedata/cifar100/augmentation_brightness_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_zoom' --save_path_pkl './noisedata/cifar100/augmentation_zoom_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_featurewise_std_normalization' --save_path_pkl './noisedata/cifar100/augmentation_featurewise_std_normalization_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_zca_whitening' --save_path_pkl './noisedata/cifar100/augmentation_zca_whitening_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_shear_range' --save_path_pkl './noisedata/cifar100/augmentation_shear_range_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'augmentation_channel_shift_range' --save_path_pkl './noisedata/cifar100/augmentation_channel_shift_range_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'noise_salt_pepper' --save_path_pkl './noisedata/cifar100/noise_salt_pepper_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'noise_gasuss' --save_path_pkl './noisedata/cifar100/noise_gasuss_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'fog' --save_path_pkl './noisedata/cifar100/fog_x.pkl' --img_np_path './data/cifar100_x.pkl'
python get_noise_data.py  --select_method 'contrast' --save_path_pkl './noisedata/cifar100/contrast_x.pkl' --img_np_path './data/cifar100_x.pkl'


