

#python main.py --path_original_out_vec './models/original_out_vec/cifa10_vgg_20_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/cifa10_vgg_20_tflite_vec.pkl' --path_embedding_vec './models/embedding_vec/cifar10_embedding.pkl' --path_y './data/cifar10_y.pkl' --path_save_res './results/original/cifa10_vgg_20_tflite.json'
#python main.py --path_original_out_vec './models/original_out_vec/cifa10_vgg_20_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/cifa10_vgg_20_coreml_vec.pkl' --path_embedding_vec './models/embedding_vec/cifar10_embedding.pkl' --path_y './data/cifar10_y.pkl' --path_save_res './results/original/cifa10_vgg_20_coreml.json'
#
#python main.py --path_original_out_vec './models/original_out_vec/cifa10_alexnet_35_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/cifa10_alexnet_35_tflite_vec.pkl' --path_embedding_vec './models/embedding_vec/cifar10_embedding.pkl' --path_y './data/cifar10_y.pkl' --path_save_res './results/original/cifa10_alexnet_35_tflite.json'
#python main.py --path_original_out_vec './models/original_out_vec/cifa10_alexnet_35_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/cifa10_alexnet_35_coreml_vec.pkl' --path_embedding_vec './models/embedding_vec/cifar10_embedding.pkl' --path_y './data/cifar10_y.pkl' --path_save_res './results/original/cifa10_alexnet_35_coreml.json'
#
#python main.py --path_original_out_vec './models/original_out_vec/fashionMnist_lenet1_3_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/fashionMnist_lenet1_3_tflite_vec.pkl' --path_embedding_vec './models/embedding_vec/fmnist_embedding.pkl' --path_y './data/fashionMnist_y.pkl' --path_save_res './results/original/fmnist_lenet1_3_tflite.json'
#python main.py --path_original_out_vec './models/original_out_vec/fashionMnist_lenet1_3_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/fashionMnist_lenet1_3_coreml_vec.pkl' --path_embedding_vec './models/embedding_vec/fmnist_embedding.pkl' --path_y './data/fashionMnist_y.pkl' --path_save_res './results/original/fmnist_lenet1_3_coreml.json'
#
#python main.py --path_original_out_vec './models/original_out_vec/fashionMnist_lenet5_3_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/fashionMnist_lenet5_3_tflite_vec.pkl' --path_embedding_vec './models/embedding_vec/fmnist_embedding.pkl' --path_y './data/fashionMnist_y.pkl' --path_save_res './results/original/fmnist_lenet5_3_tflite.json'
#python main.py --path_original_out_vec './models/original_out_vec/fashionMnist_lenet5_3_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/fashionMnist_lenet5_3_coreml_vec.pkl' --path_embedding_vec './models/embedding_vec/fmnist_embedding.pkl' --path_y './data/fashionMnist_y.pkl' --path_save_res './results/original/fmnist_lenet5_3_coreml.json'
#
#python main.py --path_original_out_vec './models/original_out_vec/plant_nin_6_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/plant_nin_6_tflite_vec.pkl' --path_embedding_vec './models/embedding_vec/plant_embedding.pkl' --path_y './data/plant_y.pkl' --path_save_res './results/original/plant_nin_6_tflite.json'
#python main.py --path_original_out_vec './models/original_out_vec/plant_nin_6_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/plant_nin_6_coreml_vec.pkl' --path_embedding_vec './models/embedding_vec/plant_embedding.pkl' --path_y './data/plant_y.pkl' --path_save_res './results/original/plant_nin_6_coreml.json'
#
#python main.py --path_original_out_vec './models/original_out_vec/plant_vgg19_20_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/plant_vgg19_20_tflite_vec.pkl' --path_embedding_vec './models/embedding_vec/plant_embedding.pkl' --path_y './data/plant_y.pkl' --path_save_res './results/original/plant_vgg19_20_tflite.json'
#python main.py --path_original_out_vec './models/original_out_vec/plant_vgg19_20_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/plant_vgg19_20_coreml_vec.pkl' --path_embedding_vec './models/embedding_vec/plant_embedding.pkl' --path_y './data/plant_y.pkl' --path_save_res './results/original/plant_vgg19_20_coreml.json'

#python main.py --path_original_out_vec './models/original_out_vec/twitter_lstm_2_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/twitter_lstm_2_tflite_vec.pkl' --path_embedding_vec './models/embedding_vec/twitter_embedding.pkl' --path_y './data/twitter_y.pkl' --path_save_res './results/original/twitter_lstm_2_tflite.json'
#python main.py --path_original_out_vec './models/original_out_vec/twitter_lstm_2_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/twitter_lstm_2_coreml_vec.pkl' --path_embedding_vec './models/embedding_vec/twitter_embedding.pkl' --path_y './data/twitter_y.pkl' --path_save_res './results/original/twitter_lstm_2_coreml.json'

#python main.py --path_original_out_vec './models/original_out_vec/twitter_gru_2_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/twitter_gru_2_tflite_vec.pkl' --path_embedding_vec './models/embedding_vec/twitter_embedding.pkl' --path_y './data/twitter_y.pkl' --path_save_res './results/original/twitter_gru_2_tflite.json'
#python main.py --path_original_out_vec './models/original_out_vec/twitter_gru_2_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/twitter_gru_2_coreml_vec.pkl' --path_embedding_vec './models/embedding_vec/twitter_embedding.pkl' --path_y './data/twitter_y.pkl' --path_save_res './results/original/twitter_gru_2_coreml.json'

python main.py --path_original_out_vec './models/original_out_vec/news_lstm_4_orginal_vec.pkl' --path_onDevice_out_vec './models/onDevice_out_vec/news_lstm_4_tflite_vec.pkl' --path_embedding_vec './models/embedding_vec/news_embedding.pkl' --path_y './data/news_y.pkl' --path_save_res './results/original/news_lstm_4_tflite.json'
